FROM pytorch/pytorch:2.4.0-cuda11.8-cudnn9-runtime

# Set working directory and copy application code
WORKDIR /app

# Install Python and pip
COPY ./req.txt /app
COPY ./AnalyzeService ./AnalyzeService
COPY ./data ./data
COPY ./DashboardService ./DashboardService

RUN pip3 install -r /app/req.txt

RUN cd ./AnalyzeService && \
    uvicorn app:app --reload --host 0.0.0.0 --port 8000

RUN cd ./DashboardService && \
     streamlit run app.py

EXPOSE 8000
EXPOSE 8501
