FROM pytorch/pytorch:2.4.0-cuda11.8-cudnn9-runtime

# Set working directory and copy application code
WORKDIR /app

# Copy src and run processes
COPY ./req.txt /app
COPY ./AnalyzeService ./AnalyzeService
COPY ./data ./data
COPY ./DashboardService ./DashboardService
COPY ./start.sh .

RUN pip3 install -r /app/req.txt

RUN sh ./start.sh

EXPOSE 8000
EXPOSE 8501
